# -*- coding: utf-8 -*-
"""Student_Attendance Tracker Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HfeKvDpzGpBdjy97-F2lIICIjYDnpuAC
"""

# Student Attendance System for Google Colab
# Run this entire code in a single Google Colab cell

# ================= INSTALL SYSTEM DEPENDENCIES FIRST =================
print("📦 Installing system dependencies...")
!apt-get install -y libzbar0 > /dev/null 2>&1

# ================= INSTALL PYTHON PACKAGES =================
print("📦 Installing Python packages...")
!pip install gradio qrcode pillow pyzbar opencv-python-headless -q

print("✅ All packages installed successfully!")
print("⏳ Starting the application...\n")

# ================= IMPORTS =================
import gradio as gr
import sqlite3
import qrcode
from datetime import datetime
from PIL import Image
import io
import os
from pyzbar.pyzbar import decode
import cv2
import numpy as np

# ================= DATABASE SETUP =================
def setup_database():
    conn = sqlite3.connect("attendance.db", check_same_thread=False)
    cursor = conn.cursor()

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS users (
        username TEXT PRIMARY KEY,
        password TEXT,
        role TEXT
    )
    """)

    cursor.execute("""
    CREATE TABLE IF NOT EXISTS attendance (
        student_username TEXT,
        date TEXT,
        time TEXT
    )
    """)

    conn.commit()
    return conn, cursor

conn, cursor = setup_database()

# ================= GLOBAL VARIABLES =================
current_user = {"username": None, "role": None}

# ================= REGISTER FUNCTION =================
def register_user(username, password, role):
    if not username or not password:
        return "❌ Error: All fields are required"

    try:
        cursor.execute(
            "INSERT INTO users VALUES (?, ?, ?)",
            (username, password, role)
        )
        conn.commit()
        return f"✅ Success! User '{username}' registered as {role}"
    except sqlite3.IntegrityError:
        return "❌ Error: Username already exists"
    except Exception as e:
        return f"❌ Error: {str(e)}"

# ================= LOGIN FUNCTION =================
def login_user(username, password):
    cursor.execute(
        "SELECT role FROM users WHERE username=? AND password=?",
        (username, password)
    )
    result = cursor.fetchone()

    if result:
        current_user["username"] = username
        current_user["role"] = result[0]
        return f"✅ Logged in successfully as {result[0]}: {username}"
    else:
        return "❌ Invalid username or password"

# ================= GENERATE QR CODE =================
def generate_qr_code():
    if current_user["role"] != "Teacher":
        return None, "❌ Only teachers can generate QR codes"

    # Create QR code with timestamp for uniqueness
    data = f"ATTENDANCE_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    qr = qrcode.QRCode(version=1, box_size=10, border=5)
    qr.add_data(data)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")

    # Save to file
    img.save("attendance_qr.png")

    return "attendance_qr.png", "✅ QR Code generated successfully! Students can scan this."

# ================= SCAN QR CODE =================
def scan_qr_code(image):
    if current_user["role"] != "Student":
        return "❌ Only students can scan QR codes"

    if image is None:
        return "❌ Please upload an image"

    try:
        # Convert image to format suitable for pyzbar
        if isinstance(image, str):
            img = cv2.imread(image)
        else:
            # Convert PIL Image to numpy array
            img = np.array(image)
            img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)

        # Decode QR code
        decoded_objects = decode(img)

        if not decoded_objects:
            return "❌ No QR code found in the image"

        qr_data = decoded_objects[0].data.decode('utf-8')

        # Check if it's a valid attendance QR
        if "ATTENDANCE" in qr_data:
            now = datetime.now()
            cursor.execute(
                "INSERT INTO attendance VALUES (?, ?, ?)",
                (current_user["username"], now.strftime("%Y-%m-%d"), now.strftime("%H:%M:%S"))
            )
            conn.commit()
            return f"✅ Attendance recorded for {current_user['username']} at {now.strftime('%H:%M:%S')}"
        else:
            return "❌ Invalid attendance QR code"

    except Exception as e:
        return f"❌ Error scanning QR code: {str(e)}"

# ================= VIEW ATTENDANCE =================
def view_attendance():
    if current_user["role"] != "Teacher":
        return "❌ Only teachers can view attendance records"

    cursor.execute("SELECT * FROM attendance ORDER BY date DESC, time DESC")
    records = cursor.fetchall()

    if not records:
        return "📋 No attendance records found"

    # Format as table
    result = "📋 **Attendance Records**\n\n"
    result += "| Student | Date | Time |\n"
    result += "|---------|------|------|\n"

    for record in records:
        result += f"| {record[0]} | {record[1]} | {record[2]} |\n"

    return result

# ================= VIEW MY ATTENDANCE (STUDENT) =================
def view_my_attendance():
    if current_user["role"] != "Student":
        return "❌ Only students can view their attendance"

    cursor.execute(
        "SELECT date, time FROM attendance WHERE student_username=? ORDER BY date DESC, time DESC",
        (current_user["username"],)
    )
    records = cursor.fetchall()

    if not records:
        return "📋 No attendance records found for you"

    result = f"📋 **Your Attendance Records**\n\n"
    result += "| Date | Time |\n"
    result += "|------|------|\n"

    for record in records:
        result += f"| {record[0]} | {record[1]} |\n"

    return result

# ================= LOGOUT =================
def logout():
    current_user["username"] = None
    current_user["role"] = None
    return "✅ Logged out successfully"

# ================= GET CURRENT USER INFO =================
def get_user_info():
    if current_user["username"]:
        return f"👤 Logged in as: **{current_user['username']}** ({current_user['role']})"
    else:
        return "👤 Not logged in"

# ================= GRADIO INTERFACE =================
with gr.Blocks(theme=gr.themes.Soft(), title="Student Attendance System") as app:

    gr.Markdown("# 🎓 Student Attendance Tracker")
    gr.Markdown("Complete attendance management system with QR code scanning")

    user_status = gr.Markdown(get_user_info())

    with gr.Tabs():

        # ===== REGISTER TAB =====
        with gr.Tab("📝 Register"):
            gr.Markdown("### Create a new account")
            with gr.Row():
                reg_username = gr.Textbox(label="Username", placeholder="Enter username")
                reg_password = gr.Textbox(label="Password", type="password", placeholder="Enter password")
            reg_role = gr.Radio(["Student", "Teacher"], label="Role", value="Student")
            reg_button = gr.Button("Register", variant="primary")
            reg_output = gr.Textbox(label="Status", interactive=False)

            reg_button.click(
                register_user,
                inputs=[reg_username, reg_password, reg_role],
                outputs=reg_output
            )

        # ===== LOGIN TAB =====
        with gr.Tab("🔐 Login"):
            gr.Markdown("### Login to your account")
            login_username = gr.Textbox(label="Username", placeholder="Enter username")
            login_password = gr.Textbox(label="Password", type="password", placeholder="Enter password")
            login_button = gr.Button("Login", variant="primary")
            login_output = gr.Textbox(label="Status", interactive=False)

            def login_and_update(username, password):
                result = login_user(username, password)
                user_info = get_user_info()
                return result, user_info

            login_button.click(
                login_and_update,
                inputs=[login_username, login_password],
                outputs=[login_output, user_status]
            )

        # ===== TEACHER DASHBOARD =====
        with gr.Tab("👨‍🏫 Teacher Dashboard"):
            gr.Markdown("### Teacher Controls")

            with gr.Row():
                gen_qr_button = gr.Button("Generate QR Code", variant="primary")
                view_att_button = gr.Button("View All Attendance", variant="secondary")

            qr_output_img = gr.Image(label="Generated QR Code", type="filepath")
            qr_output_text = gr.Textbox(label="Status", interactive=False)
            attendance_output = gr.Textbox(label="Attendance Records", interactive=False, lines=10)

            gen_qr_button.click(
                generate_qr_code,
                outputs=[qr_output_img, qr_output_text]
            )

            view_att_button.click(
                view_attendance,
                outputs=attendance_output
            )

        # ===== STUDENT DASHBOARD =====
        with gr.Tab("👨‍🎓 Student Dashboard"):
            gr.Markdown("### Student Controls")
            gr.Markdown("Upload the QR code image to mark your attendance")

            scan_image = gr.Image(label="Upload QR Code Image", type="numpy")
            scan_button = gr.Button("Scan QR Code", variant="primary")
            scan_output = gr.Textbox(label="Scan Result", interactive=False)

            view_my_att_button = gr.Button("View My Attendance", variant="secondary")
            my_attendance_output = gr.Textbox(label="My Attendance Records", interactive=False, lines=10)

            scan_button.click(
                scan_qr_code,
                inputs=scan_image,
                outputs=scan_output
            )

            view_my_att_button.click(
                view_my_attendance,
                outputs=my_attendance_output
            )

        # ===== LOGOUT TAB =====
        with gr.Tab("🚪 Logout"):
            gr.Markdown("### Logout from your account")
            logout_button = gr.Button("Logout", variant="stop")
            logout_output = gr.Textbox(label="Status", interactive=False)

            def logout_and_update():
                result = logout()
                user_info = get_user_info()
                return result, user_info

            logout_button.click(
                logout_and_update,
                outputs=[logout_output, user_status]
            )

    gr.Markdown("---")
    gr.Markdown("💡 **Instructions:**")
    gr.Markdown("""
    1. **Register**: Create an account as Student or Teacher
    2. **Login**: Login with your credentials
    3. **Teachers**: Generate QR codes and view all attendance
    4. **Students**: Download the QR code, then upload it to mark attendance
    5. **Logout**: Logout when done
    """)

# ================= LAUNCH APP =================
print("🚀 Launching application...")
app.launch(share=True, debug=True)

